### ISSUE TITLE
Standup team code review

### ISSUE THREAD

**Issue by layzrd** [pipe2442/responsivedesignProject#2]
### YOU DID AN AMAZING Work @pipe2442 and @mimipeshy 
_here are some minor stuff to be improved_

- The nav is not fixed
Yours

![yours](https://user-images.githubusercontent.com/38358081/84316710-43c8a380-ab74-11ea-9410-5a5fb7eed611.gif)

Origin
![original](https://user-images.githubusercontent.com/38358081/84316729-4d520b80-ab74-11ea-9311-ddafede59a52.gif)

-  The contents are not pretty center on mobile devices

Yours
<img width="189" alt="Screen Shot 2020-06-10 at 10 55 27 PM" src="https://user-images.githubusercontent.com/38358081/84313580-62786b80-ab6f-11ea-9f0d-9282a7d46804.png">

Original
<img width="375" alt="Screen Shot 2020-06-10 at 11 06 10 PM" src="https://user-images.githubusercontent.com/38358081/84313592-6a381000-ab6f-11ea-875e-e797bb9deb26.png">

- The fonts are not the same as the original page

Yours
<img width="413" alt="Screen Shot 2020-06-10 at 11 06 56 PM" src="https://user-images.githubusercontent.com/38358081/84313627-77ed9580-ab6f-11ea-97d6-f7ca12efb6d7.png">

Original
<img width="375" alt="Screen Shot 2020-06-10 at 11 10 47 PM" src="https://user-images.githubusercontent.com/38358081/84313917-e6325800-ab6f-11ea-8939-a2faa7acd7b3.png">

**Comment by pipe2442** [comment]
Thanks Abdu all the issues would be fixed!
